# Required options to configure
Required:
  WIFI_SSID: "your_wifi_ssid"
  WIFI_PASS: "your_wifi_pass"

  OUTPUT_GPIO_PIN: 48

# Optional confiuration, change them if you know what you're doing...
Optional:
  # Enable debug output to Serial port
  DEBUG: false

  # Delay between packets sent to server
  ACTION_DELAY: 3000

  # Device and Server UDP_PORT, 5051 is default for JavaHomeServer
  UDP_PORT: 5051

  # Settings for OTA updates, 3232:admin are defaults for JavaHomeServer
  OTA_PORT: 3232
  OTA_PASSWORD: "admin"

DEVICE_TYPE: "BasicDevice"
